<a href="https://colab.research.google.com/github/IceikSky/NM/blob/main/%D0%9B%D0%A04_%D0%92%D0%B0%D1%80%D1%96%D0%B0%D0%BD%D1%82_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Був присутній на парі. Григоришен Владислав ФІТ 2-10. Варіант 6

In [55]:
import numpy as np
np.__version__

'2.0.2'

In [56]:
matrix = np.random.randint(1, 6, size=(3,3))

matrix

array([[5, 5, 2],
       [3, 4, 2],
       [1, 1, 5]])

In [57]:
det = np.linalg.det(matrix)
det

np.float64(22.99999999999998)

In [58]:
product = np.prod(matrix)
product

np.int64(6000)

In [59]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(6000)

In [60]:
sum_1 = np.sum(matrix)
sum_1

np.int64(28)

In [61]:
np.max(matrix)

np.int64(5)

In [62]:
np.min(matrix)

np.int64(1)

In [63]:
np.mean(matrix)

np.float64(3.111111111111111)

In [64]:
max_element = np.max(matrix)
print("Найбільший елемент матриці:", max_element)
min_element = np.min(matrix)
print("Найменший елемент матриці:", min_element)

Найбільший елемент матриці: 5
Найменший елемент матриці: 1


In [65]:
np.sqrt(matrix)

array([[2.23606798, 2.23606798, 1.41421356],
       [1.73205081, 2.        , 1.41421356],
       [1.        , 1.        , 2.23606798]])

In [66]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print("Сума елементів рядка:")
print(row_sums)

Сума елементів рядка:
[[12]
 [ 9]
 [ 7]]


In [67]:
vector = np.random.randint(0, 10, size=25)
vector

array([3, 1, 7, 8, 6, 8, 5, 8, 8, 1, 5, 9, 1, 9, 3, 7, 4, 1, 1, 0, 4, 7,
       6, 3, 9])

In [71]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([9, 9, 9, 8, 8, 8, 8, 7, 7, 7, 6, 6, 5, 5, 4, 4, 3, 3, 3, 1, 1, 1,
       1, 1, 0])

In [68]:
a = np.array([[2, -1, 1], [3, 2, 7], [1, -2, 1]])
b = np.array([[2, -2, 1]])

c1 = a*b
print("Поелементний добуток матриць:")
print(c1)

Поелементний добуток матриць:
[[ 4  2  1]
 [ 6 -4  7]
 [ 2  4  1]]


In [69]:
import numpy as np

# Система рівнянь
a = np.array([[2, -1, 1], [3, 2, 7], [1, -2, 1]])
b = np.array([2, -2, 1])

# Метод Крамера
def kramer(a, b):
    det_a = np.linalg.det(a)
    if det_a != 0:
        solutions = []
        for i in range(len(a)):
            modified_a = np.copy(a)
            modified_a[:, i] = b
            solutions.append(round(np.linalg.det(modified_a) / det_a, 1))

        print('Solving a system of linear algebraic equations by Cramer\'s method:')
        print('x =', solutions)

    else:
        print('Determinant equals zero, the system has no solutions')
    return solutions

# Метод Гауса
def gaussian_elimination(a, b):
    n = len(b)
    x = np.zeros(n)

    # Прямий хід
    for k in range(n-1):
        for i in range(k+1, n):
            factor = a[i,k] / a[k,k]
            for j in range(k, n):
                a[i,j] -= factor * a[k,j]
            b[i] -= factor * b[k]

    # Обернений хід
    x[n-1] = b[n-1] / a[n-1, n-1]
    for i in range(n-2, -1, -1):
        x[i] = (b[i] - np.dot(a[i,i+1:], x[i+1:])) / a[i,i]

    print('Solving a system of linear algebraic equations by Gaussian elimination method:')
    print('x =', x.round(1))

# Матричний метод
def matrix_method(a, b):
    x = np.linalg.inv(a).dot(b)
    print('Solving a system of linear algebraic equations by matrix method:')
    print('x =', x.round(1))

# Виклик функцій для розв'язання системи
kramer(a, b)
gaussian_elimination(a, b)
matrix_method(a, b)

Solving a system of linear algebraic equations by Cramer's method:
x = [np.float64(1.2), np.float64(-0.2), np.float64(-0.8)]
Solving a system of linear algebraic equations by Gaussian elimination method:
x = [ 1.5  0.  -1. ]
Solving a system of linear algebraic equations by matrix method:
x = [ 1.5  0.  -1. ]
